'use strict';

const STORAGE_KEY='shiftwallet.v3';
const V2_KEY='shiftwallet.v2';
const LEGACY_KEY='shiftwallet.v1';
const BACKUP_KEY='shiftwallet.autobackup.v3';
const APP_VERSION=3;
const $=id=>document.getElementById(id);
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const pad=n=>String(n).padStart(2,'0');
const num=(v,f=0)=>Number.isFinite(Number(v))?Number(v):f;
const yen=n=>new Intl.NumberFormat('ja-JP',{style:'currency',currency:'JPY',maximumFractionDigits:0}).format(Math.round(num(n)));
const escapeHtml=(s='')=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const safeColor=(c,f='#3b82f6')=>/^#[0-9a-f]{6}$/i.test(String(c))?c:f;
function dateKey(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function parseDate(s){const [y,m,d]=String(s).split('-').map(Number);return new Date(y,m-1,d,12)}
function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
function addMonths(d,n){return new Date(d.getFullYear(),d.getMonth()+n,1,12)}
function daysInMonth(y,m){return new Date(y,m+1,0).getDate()}
function monthKey(d){return `${d.getFullYear()}-${pad(d.getMonth()+1)}`}
function monthLabel(d){return `${d.getFullYear()}年${d.getMonth()+1}月`}
function todayKey(){return dateKey(new Date())}
function shortDate(s){const d=parseDate(s);return `${d.getMonth()+1}/${d.getDate()}`}
function formatDateJP(s){const d=parseDate(s);return `${d.getFullYear()}/${d.getMonth()+1}/${d.getDate()}`}
function hoursText(h){return `${(Math.round(num(h)*10)/10).toLocaleString('ja-JP')}h`}
function clampDay(y,m,d){return Math.min(Math.max(1,num(d,1)),daysInMonth(y,m))}
function resolveDay(y,m,v){return v==='end'?daysInMonth(y,m):clampDay(y,m,v)}
function makeDate(y,m,v){return new Date(y,m,resolveDay(y,m,v),12)}
function startOfWeek(d){const x=new Date(d);x.setHours(12,0,0,0);x.setDate(x.getDate()-x.getDay());return x}
function downloadBlob(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

const CARD_LABELS={
 'monthly-income':'今月の収入','next-pay':'次回給与','spendable':'使えるお金','today-spend':'支出ペース','goal':'目標ガイド','quick':'シフト簡単追加','alerts':'通知','cashflow':'キャッシュフロー','recent':'直近シフト'
};
const DEFAULT_CARD_ORDER=Object.keys(CARD_LABELS);

function createDefaultWorkplace(){return {id:uid(),name:'バイト先',color:'#3b82f6',closingDay:'10',payDay:'25',payLag:0,weekendRule:'none',roundingMode:'none',roundingMinutes:1,autoBreak6:45,autoBreak8:60,transportMode:'per_shift',transportPerShift:0,transportPerKm:0,transportMonthlyCap:0,shiftAllowance:0,weekendAllowance:0,overtimeAfterHours:8,overtimeRate:1.25,nightStart:'22:00',nightEnd:'05:00',nightRate:1.25,earlyStart:'05:00',earlyEnd:'08:00',earlyRate:1}}
function defaultState(){
 const wp=createDefaultWorkplace(), account={id:uid(),name:'メイン口座',type:'bank',balance:0,isSavings:false};
 const p1={id:uid(),workplaceId:wp.id,name:'夕方 17-21',start:'17:00',end:'21:00',breakMinutes:0,useAutoBreak:false,transportOverride:null,color:wp.color};
 const p2={id:uid(),workplaceId:wp.id,name:'ロング 9-17',start:'09:00',end:'17:00',breakMinutes:60,useAutoBreak:false,transportOverride:null,color:'#16a34a'};
 return {version:3,settings:{selectedWorkplaceId:wp.id,salaryGoal:100000,goalPresetId:p1.id,balanceFloor:30000,incomeWarningLines:[1000000,1200000],theme:'system',accent:'blue',dashboardOrder:[...DEFAULT_CARD_ORDER],dashboardHidden:[],forecastHorizon:60},workplaces:[wp],wageHistory:[{id:uid(),workplaceId:wp.id,effectiveFrom:'2000-01-01',hourlyWage:1000}],presets:[p1,p2],shifts:[],fixedCosts:[],transactions:[],categoryBudgets:[],payslips:[],accounts:[account],cards:[],savingGoals:[],expenseTemplates:[]};
}
function migrateFromV2(s){
 const base=defaultState(); const wpFallback=base.workplaces[0];
 const wps=(s.workplaces||[]).length?s.workplaces:[wpFallback];
 const account={id:uid(),name:'メイン口座',type:'bank',balance:num(s.settings?.currentBalance),isSavings:false};
 const shifts=(s.shifts||[]).map(x=>{const src=x.status==='worked'&&x.actual?.start?x.actual:(x.planned||{});return {id:x.id||uid(),workplaceId:x.workplaceId||wps[0].id,date:x.date||todayKey(),planned:{start:src.start||'17:00',end:src.end||'21:00',breakMinutes:src.breakMinutes??0},useAutoBreak:false,presetId:x.presetId||'',wageOverride:x.wageOverride??null,transportOverride:x.transportOverride??null,distanceKm:num(x.distanceKm),note:x.note||''}});
 const fixed=(s.fixedCosts||[]).map(x=>({...x,isSubscription:x.isSubscription??(x.category==='サブスク'),accountId:x.accountId||account.id,cardId:x.cardId||'',priceHistory:Array.isArray(x.priceHistory)?x.priceHistory:[{from:'2000-01-01',amount:num(x.amount)}]}));
 const tx=(s.transactions||[]).length?s.transactions:(s.expenses||[]).map(x=>({id:x.id||uid(),date:x.date||todayKey(),type:'expense',name:x.name||'支出',amount:num(x.amount),category:x.category||'その他',accountId:account.id,toAccountId:'',cardId:'',note:x.note||'',receiptData:''}));
 return normalizeState({...base,...s,version:3,settings:{...base.settings,...(s.settings||{}),currentBalance:undefined},workplaces:wps.map(w=>({...createDefaultWorkplace(),...w,color:safeColor(w.color)})),presets:(s.presets||[]).map(p=>({...p,breakMinutes:p.breakMinutes??p.breakMins??0,useAutoBreak:!!p.useAutoBreak,color:safeColor(p.color,workplaceFrom(wps,p.workplaceId)?.color||'#3b82f6')})),shifts,fixedCosts:fixed,transactions:tx,accounts:(s.accounts||[]).length?s.accounts:[account],cards:s.cards||[],savingGoals:s.savingGoals||[],expenseTemplates:s.expenseTemplates||[],payslips:(s.payslips||[]).map(p=>({...p,gross:num(p.gross,p.actualAmount),net:num(p.net,p.actualAmount),tax:num(p.tax),insurance:num(p.insurance),other:num(p.other)}))});
}
function workplaceFrom(list,id){return list.find(w=>w.id===id)||list[0]}
function normalizeState(s){
 const b=defaultState(),o={...b,...s,version:3,settings:{...b.settings,...(s.settings||{})}};
 for(const k of ['workplaces','wageHistory','presets','shifts','fixedCosts','transactions','categoryBudgets','payslips','accounts','cards','savingGoals','expenseTemplates'])if(!Array.isArray(o[k]))o[k]=[];
 if(!o.workplaces.length)o.workplaces=[createDefaultWorkplace()];
 o.workplaces=o.workplaces.map(w=>({...createDefaultWorkplace(),...w,id:w.id||uid(),color:safeColor(w.color)}));
 if(!o.settings.selectedWorkplaceId||!o.workplaces.some(w=>w.id===o.settings.selectedWorkplaceId))o.settings.selectedWorkplaceId=o.workplaces[0].id;
 if(!o.accounts.length)o.accounts=[{id:uid(),name:'メイン口座',type:'bank',balance:num(s.settings?.currentBalance),isSavings:false}];
 o.accounts=o.accounts.map(a=>({id:a.id||uid(),name:a.name||'口座',type:a.type||'bank',balance:num(a.balance),isSavings:!!a.isSavings}));
 o.presets=o.presets.map(p=>({...p,id:p.id||uid(),breakMinutes:p.breakMinutes??p.breakMins??0,useAutoBreak:!!p.useAutoBreak,color:safeColor(p.color,workplaceFrom(o.workplaces,p.workplaceId)?.color)}));
 o.shifts=o.shifts.map(x=>({id:x.id||uid(),workplaceId:x.workplaceId||o.workplaces[0].id,date:x.date||todayKey(),planned:{start:x.planned?.start||x.start||'17:00',end:x.planned?.end||x.end||'21:00',breakMinutes:x.planned?.breakMinutes??x.breakMinutes??x.breakMins??0},useAutoBreak:!!x.useAutoBreak,presetId:x.presetId||'',wageOverride:x.wageOverride??null,transportOverride:x.transportOverride??null,distanceKm:num(x.distanceKm),note:x.note||''}));
 o.fixedCosts=o.fixedCosts.map(f=>({...f,id:f.id||uid(),amount:num(f.amount),isSubscription:f.isSubscription??(f.category==='サブスク'),enabled:f.enabled!==false,accountId:f.accountId||o.accounts[0].id,cardId:f.cardId||'',priceHistory:Array.isArray(f.priceHistory)&&f.priceHistory.length?f.priceHistory:[{from:'2000-01-01',amount:num(f.amount)}]}));
 o.transactions=o.transactions.map(t=>({...t,id:t.id||uid(),type:t.type||'expense',amount:Math.abs(num(t.amount)),accountId:t.accountId||o.accounts[0].id,toAccountId:t.toAccountId||'',cardId:t.cardId||'',receiptData:t.receiptData||''}));
 o.payslips=o.payslips.map(p=>({...p,id:p.id||uid(),gross:num(p.gross,p.actualAmount),net:num(p.net,p.actualAmount),tax:num(p.tax),insurance:num(p.insurance),other:num(p.other)}));
 o.settings.dashboardOrder=[...(o.settings.dashboardOrder||DEFAULT_CARD_ORDER).filter(x=>CARD_LABELS[x]),...DEFAULT_CARD_ORDER.filter(x=>!(o.settings.dashboardOrder||[]).includes(x))];
 o.settings.dashboardHidden=(o.settings.dashboardHidden||[]).filter(x=>CARD_LABELS[x]); o.settings.incomeWarningLines=(Array.isArray(o.settings.incomeWarningLines)?o.settings.incomeWarningLines:String(o.settings.incomeWarningLines||'').split(',')).map(Number).filter(x=>x>0).sort((a,b)=>a-b);
 return o;
}
function loadState(){try{const r=localStorage.getItem(STORAGE_KEY);if(r)return normalizeState(JSON.parse(r));const v2=localStorage.getItem(V2_KEY);if(v2){const m=migrateFromV2(JSON.parse(v2));localStorage.setItem(STORAGE_KEY,JSON.stringify(m));return m}const v1=localStorage.getItem(LEGACY_KEY);if(v1){const old=JSON.parse(v1),temp={settings:{currentBalance:0,salaryGoal:num(old.settings?.monthlyGoal,100000)},workplaces:[],wageHistory:[],presets:old.presets||[],shifts:old.shifts||[],fixedCosts:old.fixedCosts||[],expenses:old.expenses||[]};const m=migrateFromV2(temp);localStorage.setItem(STORAGE_KEY,JSON.stringify(m));return m}}catch(e){console.error(e)}return defaultState()}
let state=loadState();
let shiftViewMonth=new Date(new Date().getFullYear(),new Date().getMonth(),1,12),budgetViewMonth=new Date(shiftViewMonth),bulkViewMonth=new Date(shiftViewMonth),bulkSelectedDates=new Set(),selectedDay=todayKey(),suggestedDates=[],deferredInstallPrompt=null,tempReceiptData='';
function persist(render=true){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));autoBackup();applyAppearance();if(render)renderAll()}
function autoBackup(){try{const prev=JSON.parse(localStorage.getItem(BACKUP_KEY)||'null');const today=todayKey();if(!prev||prev.date!==today)localStorage.setItem(BACKUP_KEY,JSON.stringify({date:today,at:new Date().toISOString(),state}))}catch{}}
function toast(m){const e=$('toast');e.textContent=m;e.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove('show'),1800)}
function workplace(id){return state.workplaces.find(w=>w.id===id)||state.workplaces[0]}
function preset(id){return state.presets.find(p=>p.id===id)}
function account(id){return state.accounts.find(a=>a.id===id)||state.accounts[0]}
function card(id){return state.cards.find(c=>c.id===id)}
function sortedWages(wpId){return state.wageHistory.filter(w=>w.workplaceId===wpId).sort((a,b)=>a.effectiveFrom.localeCompare(b.effectiveFrom))}
function wageForDate(wpId,date){const l=sortedWages(wpId).filter(w=>w.effectiveFrom<=date);return l.length?num(l.at(-1).hourlyWage):0}
function minutesBetween(start,end){if(!start||!end)return 0;const [sh,sm]=start.split(':').map(Number),[eh,em]=end.split(':').map(Number);let a=sh*60+sm,b=eh*60+em;if(b<=a)b+=1440;return Math.max(0,b-a)}
function timeMin(t){if(!t)return 0;const [h,m]=t.split(':').map(Number);return h*60+m}
function overlap(a1,a2,b1,b2){return Math.max(0,Math.min(a2,b2)-Math.max(a1,b1))}
function windowMinutes(start,end,ws,we){if(!start||!end||!ws||!we)return 0;const s=timeMin(start);let e=timeMin(end);if(e<=s)e+=1440;const a=timeMin(ws),b0=timeMin(we),overnight=b0<=a;let total=0;for(const off of [-1440,0,1440])total+=overlap(s,e,a+off,(overnight?b0+1440:b0)+off);return Math.max(0,total)}
function autoBreakMinutes(wp,gross){if(gross>=8*60)return num(wp.autoBreak8,60);if(gross>=6*60)return num(wp.autoBreak6,45);return 0}
function roundPaidMinutes(mins,wp){const unit=Math.max(1,num(wp.roundingMinutes,1));if(wp.roundingMode==='floor')return Math.floor(mins/unit)*unit;if(wp.roundingMode==='ceil')return Math.ceil(mins/unit)*unit;if(wp.roundingMode==='nearest')return Math.round(mins/unit)*unit;return mins}
function calculateShift(s){const wp=workplace(s.workplaceId),p=s.planned||{},gross=minutesBetween(p.start,p.end),br=s.useAutoBreak?autoBreakMinutes(wp,gross):Math.max(0,num(p.breakMinutes)),paid=roundPaidMinutes(Math.max(0,gross-br),wp),wage=s.wageOverride!==null&&s.wageOverride!==''&&s.wageOverride!==undefined?num(s.wageOverride):wageForDate(s.workplaceId,s.date),night=Math.min(paid,windowMinutes(p.start,p.end,wp.nightStart,wp.nightEnd)),early=Math.min(paid,windowMinutes(p.start,p.end,wp.earlyStart,wp.earlyEnd)),ot=Math.max(0,paid-num(wp.overtimeAfterHours,8)*60),day=parseDate(s.date).getDay();let transport=0;if(s.transportOverride!==null&&s.transportOverride!==''&&s.transportOverride!==undefined)transport=num(s.transportOverride);else if(wp.transportMode==='per_shift')transport=num(wp.transportPerShift);else if(wp.transportMode==='per_km')transport=num(wp.transportPerKm)*num(s.distanceKm);const allowance=num(wp.shiftAllowance)+(day===0||day===6?num(wp.weekendAllowance):0);const pay=paid/60*wage+night/60*wage*Math.max(0,num(wp.nightRate,1.25)-1)+early/60*wage*Math.max(0,num(wp.earlyRate,1)-1)+ot/60*wage*Math.max(0,num(wp.overtimeRate,1.25)-1)+transport+allowance;return {pay:Math.round(pay),hours:paid/60,paidMinutes:paid,breakMinutes:br,wage,transport,allowance,nightMinutes:night,overtimeMinutes:ot}}
function calculatePreset(p,date=todayKey()){if(!p)return {pay:0,hours:0};return calculateShift({workplaceId:p.workplaceId,date,planned:{start:p.start,end:p.end,breakMinutes:p.breakMinutes??0},useAutoBreak:!!p.useAutoBreak,wageOverride:null,transportOverride:p.transportOverride,distanceKm:0})}
function sumShifts(list){
 const out={pay:0,hours:0},transportByGroup=new Map();
 for(const s of list){const c=calculateShift(s);out.pay+=c.pay;out.hours+=c.hours;const k=`${s.workplaceId}:${s.date.slice(0,7)}`;transportByGroup.set(k,(transportByGroup.get(k)||0)+c.transport)}
 for(const [k,total] of transportByGroup){const wp=workplace(k.split(':')[0]),cap=num(wp.transportMonthlyCap);if(cap>0&&total>cap)out.pay-=total-cap}
 return out;
}

function cycleForShift(wp,dateStr){const d=parseDate(dateStr);let close;if(wp.closingDay==='end')close=makeDate(d.getFullYear(),d.getMonth(),'end');else{const cd=num(wp.closingDay,31);close=d.getDate()<=resolveDay(d.getFullYear(),d.getMonth(),cd)?makeDate(d.getFullYear(),d.getMonth(),cd):makeDate(d.getFullYear(),d.getMonth()+1,cd)}const prev=wp.closingDay==='end'?makeDate(close.getFullYear(),close.getMonth()-1,'end'):makeDate(close.getFullYear(),close.getMonth()-1,wp.closingDay);return {start:dateKey(addDays(prev,1)),end:dateKey(close),closeDate:dateKey(close)}}
function adjustWeekend(d,rule){const x=new Date(d);if(rule==='previous')while([0,6].includes(x.getDay()))x.setDate(x.getDate()-1);if(rule==='next')while([0,6].includes(x.getDay()))x.setDate(x.getDate()+1);return x}
function payDateForClose(wp,close){const c=parseDate(close),base=new Date(c.getFullYear(),c.getMonth()+num(wp.payLag),1,12);return dateKey(adjustWeekend(makeDate(base.getFullYear(),base.getMonth(),wp.payDay),wp.weekendRule))}
function cyclesAroundWorkplace(wp,center=new Date(),back=8,forward=14){const out=[];for(let i=-back;i<=forward;i++){const m=addMonths(new Date(center.getFullYear(),center.getMonth(),1,12),i),close=makeDate(m.getFullYear(),m.getMonth(),wp.closingDay),prev=wp.closingDay==='end'?makeDate(close.getFullYear(),close.getMonth()-1,'end'):makeDate(close.getFullYear(),close.getMonth()-1,wp.closingDay),c={start:dateKey(addDays(prev,1)),end:dateKey(close),closeDate:dateKey(close)};c.payDate=payDateForClose(wp,c.closeDate);out.push(c)}return out.sort((a,b)=>a.payDate.localeCompare(b.payDate))}
function nextPayCycle(wp,from=todayKey()){return cyclesAroundWorkplace(wp,parseDate(from),10,18).find(c=>c.payDate>=from)||cyclesAroundWorkplace(wp,parseDate(from),2,30).at(-1)}
function cycleByPayDate(wp,pd){return cyclesAroundWorkplace(wp,parseDate(pd),20,10).find(c=>c.payDate===pd)||null}
function cycleStats(wpId,c){const list=state.shifts.filter(s=>s.workplaceId===wpId&&s.date>=c.start&&s.date<=c.end),forecast=sumShifts(list),current=sumShifts(list.filter(s=>s.date<=todayKey()));return {list,forecast:forecast.pay,current:current.pay,hours:forecast.hours,currentHours:current.hours}}
function currentMonthStats(wpId='all'){const key=monthKey(new Date()),list=state.shifts.filter(s=>s.date.startsWith(key)&&(wpId==='all'||s.workplaceId===wpId)),all=sumShifts(list),cur=sumShifts(list.filter(s=>s.date<=todayKey()));return {list,forecast:all.pay,current:cur.pay,hours:all.hours,currentHours:cur.hours}}
function shiftsInMonth(d,wpFilter='all'){const k=monthKey(d);return state.shifts.filter(s=>s.date.startsWith(k)&&(wpFilter==='all'||s.workplaceId===wpFilter)).sort((a,b)=>a.date.localeCompare(b.date)||(a.planned?.start||'').localeCompare(b.planned?.start||''))}

function fixedAmountOn(f,date){const h=[...(f.priceHistory||[])].filter(x=>x.from<=date).sort((a,b)=>a.from.localeCompare(b.from));return h.length?num(h.at(-1).amount):num(f.amount)}
function fixedOccurrenceDate(f,y,m){return dateKey(makeDate(y,m,f.day||'1'))}
function cardPayDateForExpense(cd,date){const d=parseDate(date);let close;const day=cd.closingDay==='end'?daysInMonth(d.getFullYear(),d.getMonth()):num(cd.closingDay,31);if(d.getDate()<=clampDay(d.getFullYear(),d.getMonth(),day))close=makeDate(d.getFullYear(),d.getMonth(),cd.closingDay);else close=makeDate(d.getFullYear(),d.getMonth()+1,cd.closingDay);const base=new Date(close.getFullYear(),close.getMonth()+num(cd.payLag,1),1,12);return dateKey(makeDate(base.getFullYear(),base.getMonth(),cd.payDay||'27'))}
function fixedOccurrencesBetween(start,end){const a=parseDate(start),b=parseDate(end),ev=[];for(const f of state.fixedCosts.filter(x=>x.enabled!==false)){let cur=new Date(a.getFullYear(),a.getMonth(),1,12),last=new Date(b.getFullYear(),b.getMonth(),1,12);while(cur<=last){if(f.recurrence==='monthly'||(f.recurrence==='yearly'&&num(f.month)===cur.getMonth()+1)){const purchase=fixedOccurrenceDate(f,cur.getFullYear(),cur.getMonth()),amount=fixedAmountOn(f,purchase);let date=purchase,type='fixed';if(f.cardId&&card(f.cardId)){date=cardPayDateForExpense(card(f.cardId),purchase);type='card'}if(date>=start&&date<=end)ev.push({date,type,name:f.name,category:f.category||'固定費',amount:-Math.abs(amount),refId:f.id})}cur=addMonths(cur,1)}}return ev}
function transactionCashEvents(start,end){const ev=[];for(const t of state.transactions){if(t.type==='transfer')continue;let date=t.date;if(t.type==='expense'&&t.cardId&&card(t.cardId))date=cardPayDateForExpense(card(t.cardId),t.date);if(date<start||date>end)continue;ev.push({date,type:t.cardId?'card':t.type,name:t.name,category:t.category,amount:t.type==='income'?Math.abs(num(t.amount)):-Math.abs(num(t.amount)),refId:t.id})}return ev}
function salaryEventsBetween(start,end){const ev=[];for(const wp of state.workplaces)for(const c of cyclesAroundWorkplace(wp,parseDate(start),10,14)){if(c.payDate<start||c.payDate>end)continue;const st=cycleStats(wp.id,c),slip=state.payslips.find(p=>p.workplaceId===wp.id&&p.payDate===c.payDate),amount=slip?num(slip.net):st.forecast;if(amount)ev.push({date:c.payDate,type:'salary',name:`${wp.name} 給与`,category:'給与',amount:Math.abs(amount),workplaceId:wp.id,cycle:c})}return ev}
function cashflowEvents(start,end){return [...salaryEventsBetween(start,end),...fixedOccurrencesBetween(start,end),...transactionCashEvents(start,end)].sort((a,b)=>a.date.localeCompare(b.date)||b.amount-a.amount)}
function totalAssets(){return state.accounts.reduce((s,a)=>s+num(a.balance),0)}
function spendableAssets(){return state.accounts.filter(a=>!a.isSavings).reduce((s,a)=>s+num(a.balance),0)}
function expenseTransactionsInMonth(d){const k=monthKey(d);return state.transactions.filter(t=>t.type==='expense'&&t.date.startsWith(k))}
function incomeTransactionsInMonth(d){const k=monthKey(d);return state.transactions.filter(t=>t.type==='income'&&t.date.startsWith(k))}
function fixedMonthTotal(d){const start=dateKey(new Date(d.getFullYear(),d.getMonth(),1,12)),end=dateKey(new Date(d.getFullYear(),d.getMonth()+1,0,12));return fixedOccurrencesBetween(start,end).filter(e=>e.type!=='card'||e.date.startsWith(monthKey(d))).reduce((s,e)=>s+Math.abs(e.amount),0)}
function cardBillMonthTotal(d){const k=monthKey(d),start=`${k}-01`,end=dateKey(new Date(d.getFullYear(),d.getMonth()+1,0,12));return [...transactionCashEvents(start,end),...fixedOccurrencesBetween(start,end)].filter(e=>e.type==='card').reduce((s,e)=>s+Math.abs(e.amount),0)}

function applyAppearance(){document.documentElement.dataset.theme=state.settings.theme||'system';document.documentElement.dataset.accent=state.settings.accent||'blue'}
function applyDashboardLayout(){const root=$('page-dashboard');for(const id of state.settings.dashboardOrder){const el=root.querySelector(`[data-home-card="${id}"]`);if(el)root.appendChild(el)}root.querySelectorAll('[data-home-card]').forEach(el=>el.hidden=(state.settings.dashboardHidden||[]).includes(el.dataset.homeCard))}
function renderSelects(){const wpOpts=state.workplaces.map(w=>`<option value="${w.id}">${escapeHtml(w.name)}</option>`).join('');for(const id of ['dashboardWorkplace','wageWorkplace','presetWorkplace','shiftWorkplace','bulkWorkplace','payslipWorkplace']){const el=$(id);if(el){const v=el.value;el.innerHTML=wpOpts;if(state.workplaces.some(w=>w.id===v))el.value=v}}$('shiftWorkplaceFilter').innerHTML=`<option value="all">すべての勤務先</option>${wpOpts}`;$('dashboardWorkplace').value=state.settings.selectedWorkplaceId;const dayOpts=Array.from({length:31},(_,i)=>`<option value="${i+1}">${i+1}日</option>`).join('')+'<option value="end">月末</option>';for(const id of ['closingDay','payDay','fixedDay'])if($(id)&&!$(id).dataset.ready){$(id).innerHTML=dayOpts;$(id).dataset.ready='1'}if($('fixedMonth')&&!$('fixedMonth').dataset.ready){$('fixedMonth').innerHTML=Array.from({length:12},(_,i)=>`<option value="${i+1}">${i+1}月</option>`).join('');$('fixedMonth').dataset.ready='1'}renderAccountCardSelects();renderPresetSelects()}
function renderAccountCardSelects(){const acc=state.accounts.map(a=>`<option value="${a.id}">${escapeHtml(a.name)}</option>`).join(''),cards='<option value="">使わない</option>'+state.cards.map(c=>`<option value="${c.id}">${escapeHtml(c.name)}</option>`).join('');for(const id of ['transactionAccount','fixedAccount'])if($(id)){const v=$(id).value;$(id).innerHTML=acc;if(state.accounts.some(a=>a.id===v))$(id).value=v}for(const id of ['transactionCard','fixedCard'])if($(id)){const v=$(id).value;$(id).innerHTML=cards;if(!v||state.cards.some(c=>c.id===v))$(id).value=v}}
function renderPresetSelects(){const sw=$('shiftWorkplace')?.value||state.settings.selectedWorkplaceId,sp=state.presets.filter(p=>p.workplaceId===sw);if($('shiftPreset'))$('shiftPreset').innerHTML='<option value="">手入力</option>'+sp.map(p=>`<option value="${p.id}">${escapeHtml(p.name)}</option>`).join('');const bw=$('bulkWorkplace')?.value||state.settings.selectedWorkplaceId,bp=state.presets.filter(p=>p.workplaceId===bw);if($('bulkPreset'))$('bulkPreset').innerHTML=bp.map(p=>`<option value="${p.id}">${escapeHtml(p.name)}</option>`).join('');const gp=state.presets.filter(p=>p.workplaceId===state.settings.selectedWorkplaceId);$('goalPreset').innerHTML=gp.length?gp.map(p=>`<option value="${p.id}">${escapeHtml(p.name)}</option>`).join(''):'<option value="">なし</option>';if(gp.some(p=>p.id===state.settings.goalPresetId))$('goalPreset').value=state.settings.goalPresetId;else if(gp[0])state.settings.goalPresetId=gp[0].id}

function renderDashboard(){
 const wp=workplace(state.settings.selectedWorkplaceId),month=currentMonthStats(wp.id);$('monthlyForecast').textContent=yen(month.forecast);$('monthlyCurrent').textContent=yen(month.current);$('monthlyHours').textContent=hoursText(month.hours);$('monthlyCurrentHours').textContent=hoursText(month.currentHours);const weekStart=dateKey(startOfWeek(new Date())),weekEnd=dateKey(addDays(startOfWeek(new Date()),6));$('weeklyWorkHours').textContent=hoursText(sumShifts(state.shifts.filter(s=>s.workplaceId===wp.id&&s.date>=weekStart&&s.date<=weekEnd)).hours);$('monthIncomeLabel').textContent=`${new Date().getMonth()+1}月`;
 const c=nextPayCycle(wp),st=cycleStats(wp.id,c),goal=num(state.settings.salaryGoal),remain=Math.max(0,goal-st.forecast),pct=goal?Math.min(100,Math.round(st.forecast/goal*100)):0;$('nextPayForecast').textContent=yen(st.forecast);$('nextPayCurrent').textContent=yen(st.current);$('nextPayDate').textContent=formatDateJP(c.payDate);$('nextPayPeriod').textContent=`対象期間 ${formatDateJP(c.start)}〜${formatDateJP(c.end)}`;$('goalAmount').textContent=yen(goal);$('remainingToGoal').textContent=yen(remain);$('goalPercent').textContent=`${pct}%`;$('goalProgress').style.width=`${pct}%`;$('cycleHours').textContent=hoursText(st.hours);
 const gp=preset(state.settings.goalPresetId),pc=gp?calculatePreset(gp,c.end):{pay:0,hours:0},need=pc.pay>0?Math.ceil(remain/pc.pay):0;$('neededShifts').textContent=remain<=0?'達成':pc.pay?`${need}回`:'—';$('goalGuide').innerHTML=gp&&pc.pay?`<div class="big-guide-number">${remain<=0?'目標達成':`あと ${need} 回`}</div><p class="muted">「${escapeHtml(gp.name)}」1回 約 <b>${yen(pc.pay)}</b> / ${hoursText(pc.hours)}</p><div class="guide-subgrid"><div><span>不足額</span><b>${yen(remain)}</b></div><div><span>必要勤務時間</span><b>${hoursText(need*pc.hours)}</b></div></div>`:'<div class="empty">目標用プリセットを設定してください</div>';
 $('goalPresetComparison').innerHTML=state.presets.filter(p=>p.workplaceId===wp.id).slice(0,5).map(p=>{const x=calculatePreset(p,c.end),n=x.pay?Math.ceil(remain/x.pay):0;return `<div class="compact-row"><span>${escapeHtml(p.name)}</span><b>${remain<=0?'達成':x.pay?`あと${n}回 / ${hoursText(n*x.hours)}`:'—'}</b></div>`}).join('');
 const dayBefore=dateKey(addDays(parseDate(c.payDate),-1)),flows=dayBefore>=todayKey()?cashflowEvents(todayKey(),dayBefore):[],available=spendableAssets()+flows.reduce((s,e)=>s+e.amount,0),days=Math.max(1,Math.ceil((parseDate(c.payDate)-parseDate(todayKey()))/86400000));$('totalAssetsHome').textContent=yen(totalAssets());$('assetBreakdownHome').textContent=`自由資金 ${yen(spendableAssets())} / 貯金 ${yen(totalAssets()-spendableAssets())}`;$('spendableUntilPay').textContent=yen(available);$('spendableUntilPay').className=available<0?'negative':'';$('spendableNote').textContent=`${shortDate(c.payDate)}までの予定を反映`;$('dailySpendable').textContent=yen(Math.max(0,available-num(state.settings.balanceFloor))/days);const buffer=spendableAssets()-num(state.settings.balanceFloor);$('floorBuffer').textContent=yen(buffer);$('floorBuffer').className=buffer<0?'negative':'';$('floorNote').textContent=`最低残高 ${yen(state.settings.balanceFloor)}`;
 const t=todayKey(),ws=dateKey(startOfWeek(new Date())),we=dateKey(addDays(startOfWeek(new Date()),6));$('todaySpending').textContent=yen(state.transactions.filter(x=>x.type==='expense'&&x.date===t).reduce((s,x)=>s+num(x.amount),0));$('weekSpending').textContent=yen(state.transactions.filter(x=>x.type==='expense'&&x.date>=ws&&x.date<=we).reduce((s,x)=>s+num(x.amount),0));$('spendingPaceAlerts').innerHTML=spendingAlertsHtml();
 const q=state.presets.filter(p=>p.workplaceId===wp.id);$('quickPresetList').innerHTML=q.length?q.map(p=>{const x=calculatePreset(p,$('quickDate').value||todayKey());return `<button class="preset-chip" style="border-left:4px solid ${safeColor(p.color,wp.color)}" type="button" data-quick-preset="${p.id}"><b>${escapeHtml(p.name)}</b><span>${p.start}–${p.end} / 休憩${p.useAutoBreak?'自動':`${num(p.breakMinutes)}分`} / 約${yen(x.pay)}</span></button>`}).join(''):'<div class="empty">プリセットがありません</div>';
 $('homeAlerts').innerHTML=homeAlertsHtml(c);$('cashflowPreview').innerHTML=cashflowEvents(todayKey(),dateKey(addDays(new Date(),30))).slice(0,7).map(e=>timelineHtml(e)).join('')||'<div class="empty">今後30日の予定はありません</div>';$('recentShifts').innerHTML=[...state.shifts].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5).map(shiftItemHtml).join('')||'<div class="empty">まだシフトがありません</div>';applyDashboardLayout();
}
function spendingAlertsHtml(){const d=new Date(),elapsed=d.getDate(),total=daysInMonth(d.getFullYear(),d.getMonth()),ex=expenseTransactionsInMonth(d),alerts=[];for(const b of state.categoryBudgets){const spent=ex.filter(x=>x.category===b.category).reduce((s,x)=>s+num(x.amount),0),projected=elapsed?spent/elapsed*total:spent;if(num(b.amount)>0&&projected>num(b.amount))alerts.push(`<div class="alert-item warn"><b>${escapeHtml(b.category)}は使いすぎペース</b>現在 ${yen(spent)} / 月末予測 ${yen(projected)}（予算 ${yen(b.amount)}）</div>`)}return alerts.join('')||'<div class="alert-item good"><b>予算ペース</b>現在、大きな超過予測はありません。</div>'}
function nextFixedOccurrence(f){const start=todayKey(),end=dateKey(addDays(new Date(),45));return fixedOccurrencesBetween(start,end).find(e=>e.refId===f.id)}
function homeAlertsHtml(c){const a=[];for(const f of state.fixedCosts.filter(x=>x.enabled!==false)){const e=nextFixedOccurrence(f);if(e){const days=Math.round((parseDate(e.date)-parseDate(todayKey()))/86400000);if(days<=7)a.push(`<div class="alert-item"><b>${escapeHtml(f.name)} ${yen(Math.abs(e.amount))}</b>${days===0?'今日':`${days}日後`}に支払い予定</div>`)}}const annual=annualScheduledIncome(new Date().getFullYear()),line=(state.settings.incomeWarningLines||[]).find(x=>annual>=x*.9&&annual<x);if(line)a.push(`<div class="alert-item warn"><b>年間収入ラインに接近</b>${yen(line)}まであと ${yen(line-annual)}</div>`);if(spendableAssets()<num(state.settings.balanceFloor))a.push(`<div class="alert-item bad"><b>最低残高を下回っています</b>自由資金 ${yen(spendableAssets())}</div>`);return a.join('')||'<div class="alert-item good"><b>通知なし</b>直近の支払い・残高に大きな警告はありません。</div>'}
function timelineHtml(e,balance=null){const pos=e.amount>=0;return `<div class="timeline-item"><div class="timeline-date">${shortDate(e.date)}</div><div class="timeline-name">${escapeHtml(e.name)}<small>${e.type==='salary'?'給与':escapeHtml(e.category||e.type)}</small></div><div class="timeline-amount ${pos?'positive':'negative'}">${pos?'+':'−'}${yen(Math.abs(e.amount))}${balance===null?'':`<span class="timeline-balance">残高 ${yen(balance)}</span>`}</div></div>`}
function shiftItemHtml(s){const w=workplace(s.workplaceId),c=calculateShift(s),p=s.planned||{},col=safeColor(preset(s.presetId)?.color,w.color);return `<div class="list-item"><div class="list-main"><div class="list-title"><span class="shift-color-dot" style="--dot-color:${col}"></span>${escapeHtml(s.date)} ${escapeHtml(w.name)}</div><div class="list-sub">${p.start||'—'}–${p.end||'—'} / 休憩${s.useAutoBreak?`自動(${c.breakMinutes}分)`:num(p.breakMinutes)+'分'} / ${hoursText(c.hours)}${s.note?`<br>${escapeHtml(s.note)}`:''}</div></div><div class="list-value"><b>${yen(c.pay)}</b><small>時給 ${yen(c.wage)}</small><div class="item-actions"><button class="mini-link" data-copy-week="${s.id}">翌週</button><button class="mini-link" data-copy-four="${s.id}">4週</button><button class="mini-link" data-edit-shift="${s.id}">編集</button><button class="mini-link danger" data-delete-shift="${s.id}">削除</button></div></div></div>`}

function renderShifts(){const filter=$('shiftWorkplaceFilter').value||'all',list=shiftsInMonth(shiftViewMonth,filter),sum=sumShifts(list);$('monthTitle').textContent=monthLabel(shiftViewMonth);$('monthlyShiftList').innerHTML=list.map(shiftItemHtml).join('')||'<div class="empty">この月のシフトはありません</div>';$('monthlyHoursTotal').textContent=hoursText(sum.hours);$('monthlyShiftIncome').textContent=yen(sum.pay);renderCalendar(list)}
function renderCalendar(list){const y=shiftViewMonth.getFullYear(),m=shiftViewMonth.getMonth(),start=addDays(new Date(y,m,1,12),-new Date(y,m,1,12).getDay()),today=todayKey();let h='';for(let i=0;i<42;i++){const d=addDays(start,i),k=dateKey(d),ss=list.filter(s=>s.date===k),outside=d.getMonth()!==m,total=sumShifts(ss).pay;h+=`<div class="calendar-day ${outside?'outside':''} ${k===today?'today':''} ${ss.length?'has-shifts':''}" data-calendar-date="${k}"><span class="day-number">${d.getDate()}</span>${ss.slice(0,2).map(s=>{const col=safeColor(preset(s.presetId)?.color,workplace(s.workplaceId).color);return `<div class="day-chip" style="--chip-color:${col}"><span class="chip-time">${s.planned?.start||''}</span><span class="chip-workplace">${escapeHtml(workplace(s.workplaceId).name)}</span></div>`}).join('')}${ss.length>2?`<div class="day-chip">+${ss.length-2}</div>`:''}${ss.length?`<span class="day-total">${yen(total)}</span>`:''}</div>`}$('calendarGrid').innerHTML=h}
function renderBulkCalendar(){const y=bulkViewMonth.getFullYear(),m=bulkViewMonth.getMonth();$('bulkMonthTitle').textContent=monthLabel(bulkViewMonth);const start=addDays(new Date(y,m,1,12),-new Date(y,m,1,12).getDay()),p=preset($('bulkPreset')?.value);let h='';for(let i=0;i<42;i++){const d=addDays(start,i),k=dateKey(d),outside=d.getMonth()!==m,selected=bulkSelectedDates.has(k),count=state.shifts.filter(x=>x.date===k&&(!p||x.workplaceId===p.workplaceId)).length;h+=`<button type="button" class="bulk-calendar-day ${outside?'outside':''} ${k===todayKey()?'today':''} ${selected?'selected':''}" data-bulk-date="${k}" ${outside?'disabled':''}><span class="bulk-day-number">${d.getDate()}</span>${count?`<small>${count}件あり</small>`:''}</button>`}$('bulkCalendarGrid').innerHTML=h;updateBulkSelectionSummary()}
function updateBulkSelectionSummary(){const n=bulkSelectedDates.size;$('bulkSelectedCount').textContent=`${n}日`;$('bulkSubmitBtn').disabled=!n;$('bulkSubmitBtn').textContent=n?`選択した${n}日に追加`:'選択した日に追加';const ds=[...bulkSelectedDates].sort();$('bulkSelectionHint').textContent=n?`${ds[0].replaceAll('-','/')}〜${ds.at(-1).replaceAll('-','/')} のうち ${n}日を選択中。同じ日に別シフトがあっても追加できます。`:'追加したい日付をタップしてください。同じ日に複数シフトも登録できます。'}
function openBulkShiftPicker(){ $('bulkWorkplace').value=state.settings.selectedWorkplaceId;renderPresetSelects();bulkSelectedDates=new Set();bulkViewMonth=new Date(shiftViewMonth);renderBulkCalendar();openDialog('bulkShiftModal')}
function openDayShift(date){selectedDay=date;const list=state.shifts.filter(s=>s.date===date).sort((a,b)=>(a.planned.start||'').localeCompare(b.planned.start||'')),sum=sumShifts(list);$('dayShiftTitle').textContent=`${formatDateJP(date)} のシフト`;$('dayShiftSummary').innerHTML=`<span>${list.length}件</span><b>${hoursText(sum.hours)}</b><span>見込み</span><b>${yen(sum.pay)}</b>`;$('dayShiftList').innerHTML=list.map(shiftItemHtml).join('')||'<div class="empty">シフトはありません</div>';openDialog('dayShiftModal')}

function renderBudget(){const ex=expenseTransactionsInMonth(budgetViewMonth),inc=incomeTransactionsInMonth(budgetViewMonth),fixed=fixedMonthTotal(budgetViewMonth);$('budgetMonthTitle').textContent=monthLabel(budgetViewMonth);$('budgetExpense').textContent=yen(ex.reduce((s,x)=>s+num(x.amount),0));$('budgetIncome').textContent=yen(inc.reduce((s,x)=>s+num(x.amount),0));$('budgetFixed').textContent=yen(fixed);$('budgetCardBill').textContent=yen(cardBillMonthTotal(budgetViewMonth));
 $('expenseTemplateStrip').innerHTML=state.expenseTemplates.length?state.expenseTemplates.map(t=>`<button class="preset-chip" data-use-template="${t.id}"><b>${escapeHtml(t.name)}</b><span>${yen(t.amount)} / ${escapeHtml(t.category)}</span></button>`).join(''):'<div class="empty">テンプレートを追加するとワンタップ入力できます</div>';renderMoneyCalendar();renderAccounts();renderCards();renderSavingGoals();renderCategoryBudgets(ex);renderFixedCosts();renderTransactions();renderFutureBalance();renderPayslips()}
function renderMoneyCalendar(){const y=budgetViewMonth.getFullYear(),m=budgetViewMonth.getMonth(),start=addDays(new Date(y,m,1,12),-new Date(y,m,1,12).getDay()),end=dateKey(addDays(start,41)),events=cashflowEvents(dateKey(start),end);let h='';for(let i=0;i<42;i++){const d=addDays(start,i),k=dateKey(d),es=events.filter(e=>e.date===k),net=es.reduce((s,e)=>s+e.amount,0),outside=d.getMonth()!==m;h+=`<div class="money-day ${outside?'outside':''}"><span class="n">${d.getDate()}</span>${es.length?`<div class="net ${net>=0?'pos':'neg'}">${net>=0?'+':''}${yen(net)}</div><small>${es.length}件</small>`:''}</div>`}$('moneyCalendarGrid').innerHTML=h}
function renderAccounts(){$('accountList').innerHTML=state.accounts.map(a=>`<div class="list-item"><div class="list-main"><div class="list-title">${escapeHtml(a.name)} ${a.isSavings?'<span class="tag">貯金</span>':''}</div><div class="list-sub">${a.type==='cash'?'現金':a.type==='emoney'?'電子マネー':'銀行・口座'}</div></div><div class="list-value"><b>${yen(a.balance)}</b><div class="item-actions"><button class="mini-link" data-edit-account="${a.id}">編集</button><button class="mini-link danger" data-delete-account="${a.id}">削除</button></div></div></div>`).join('')}
function nextCardBill(c){const from=todayKey(),end=dateKey(addDays(new Date(),75)),events=state.transactions.filter(t=>t.type==='expense'&&t.cardId===c.id).map(t=>({date:cardPayDateForExpense(c,t.date),amount:num(t.amount)}));const fixed=[];for(const f of state.fixedCosts.filter(f=>f.cardId===c.id&&f.enabled!==false))fixed.push(...fixedOccurrencesBetween(from,end).filter(e=>e.refId===f.id).map(e=>({date:e.date,amount:Math.abs(e.amount)})));const all=[...events,...fixed].filter(e=>e.date>=from).sort((a,b)=>a.date.localeCompare(b.date)),date=all[0]?.date,total=date?all.filter(x=>x.date===date).reduce((s,x)=>s+x.amount,0):0;return {date,total}}
function renderCards(){$('cardList').innerHTML=state.cards.length?state.cards.map(c=>{const b=nextCardBill(c);return `<div class="list-item"><div class="list-main"><div class="list-title">${escapeHtml(c.name)}</div><div class="list-sub">${c.closingDay==='end'?'月末':c.closingDay+'日'}締め / ${c.payDay}日払い / 引落 ${escapeHtml(account(c.accountId).name)}</div></div><div class="list-value"><b>${b.date?yen(b.total):'—'}</b><small>${b.date?formatDateJP(b.date):'次回請求なし'}</small><div class="item-actions"><button class="mini-link" data-edit-card="${c.id}">編集</button><button class="mini-link danger" data-delete-card="${c.id}">削除</button></div></div></div>`}).join(''):'<div class="empty">カードを登録すると利用日と引落日を分けて予測できます</div>'}
function avgMonthlySurplus(){const months=Array.from({length:3},(_,i)=>addMonths(new Date(new Date().getFullYear(),new Date().getMonth(),1,12),-i-1)),vals=months.map(m=>currentMonthStats('all').forecast);const incomes=months.map(m=>shiftsInMonth(m,'all').reduce((s,x)=>s+calculateShift(x).pay,0)+incomeTransactionsInMonth(m).reduce((s,x)=>s+num(x.amount),0)),spends=months.map(m=>expenseTransactionsInMonth(m).reduce((s,x)=>s+num(x.amount),0)+fixedMonthTotal(m));return Math.max(0,(incomes.reduce((a,b)=>a+b,0)-spends.reduce((a,b)=>a+b,0))/months.length)}
function renderSavingGoals(){const surplus=avgMonthlySurplus();$('savingGoalList').innerHTML=state.savingGoals.length?state.savingGoals.map(g=>{const rem=Math.max(0,num(g.target)-num(g.current)),monthly=num(g.monthlyContribution)||surplus,months=monthly>0?Math.ceil(rem/monthly):null,pct=num(g.target)>0?Math.min(100,Math.round(num(g.current)/num(g.target)*100)):0;return `<div class="list-item"><div class="list-main"><div class="list-title">${escapeHtml(g.name)}</div><div class="list-sub">${yen(g.current)} / ${yen(g.target)}（${pct}%）${months!==null?` / 約${months}か月` : ''}</div><div class="budget-track"><div class="budget-fill" style="width:${pct}%"></div></div></div><div class="list-value"><b>あと ${yen(rem)}</b><div class="item-actions"><button class="mini-link" data-edit-goal="${g.id}">編集</button><button class="mini-link danger" data-delete-goal="${g.id}">削除</button></div></div></div>`}).join(''):'<div class="empty">欲しいもの・旅行・緊急資金など複数目標を管理できます</div>'}
function renderCategoryBudgets(ex){$('categoryBudgetList').innerHTML=state.categoryBudgets.length?state.categoryBudgets.map(b=>{const spent=ex.filter(e=>e.category===b.category).reduce((s,e)=>s+num(e.amount),0),pct=num(b.amount)>0?Math.round(spent/num(b.amount)*100):0;return `<div class="list-item"><div class="list-main"><div class="list-title">${escapeHtml(b.category)}</div><div class="budget-progress"><div class="budget-progress-head"><span>${yen(spent)} / ${yen(b.amount)}</span><span>${pct}%</span></div><div class="budget-track"><div class="budget-fill ${pct>100?'over':''}" style="width:${Math.min(100,pct)}%"></div></div></div></div><div class="list-value"><b class="${pct>100?'negative':''}">${pct>100?'超過':'残り'} ${yen(Math.abs(num(b.amount)-spent))}</b><div class="item-actions"><button class="mini-link" data-edit-budget="${escapeHtml(b.category)}">編集</button><button class="mini-link danger" data-delete-budget="${escapeHtml(b.category)}">削除</button></div></div></div>`}).join(''):'<div class="empty">カテゴリ予算を登録すると使いすぎを予測します</div>'}
function renderFixedCosts(){const subs=state.fixedCosts.filter(f=>f.isSubscription&&f.enabled!==false),annual=subs.reduce((s,f)=>s+(f.recurrence==='monthly'?fixedAmountOn(f,todayKey())*12:fixedAmountOn(f,todayKey())),0);$('subscriptionSummary').innerHTML=`<span>サブスク年間</span><b>${yen(annual)}</b><span>月平均</span><b>${yen(annual/12)}</b>`;$('fixedCostList').innerHTML=state.fixedCosts.length?state.fixedCosts.map(f=>{const amt=fixedAmountOn(f,todayKey()),year=f.recurrence==='monthly'?amt*12:amt;return `<div class="list-item"><div class="list-main"><div class="list-title">${escapeHtml(f.name)} ${f.isSubscription?'<span class="tag">サブスク</span>':''}</div><div class="list-sub">${f.recurrence==='monthly'?'毎月':'毎年'} ${f.day==='end'?'月末':f.day+'日'} / 年間 ${yen(year)} / 価格履歴${f.priceHistory?.length||1}件</div></div><div class="list-value"><b>${yen(amt)}</b><div class="item-actions"><button class="mini-link" data-edit-fixed="${f.id}">編集</button><button class="mini-link" data-toggle-fixed="${f.id}">${f.enabled===false?'再開':'停止'}</button><button class="mini-link danger" data-delete-fixed="${f.id}">削除</button></div></div></div>`}).join(''):'<div class="empty">固定費・サブスクはまだありません</div>'}
function renderTransactions(){const k=monthKey(budgetViewMonth),l=state.transactions.filter(t=>t.date.startsWith(k)).sort((a,b)=>b.date.localeCompare(a.date));$('transactionList').innerHTML=l.length?l.map(t=>`<div class="list-item"><div class="list-main"><div class="list-title">${escapeHtml(t.name)} <span class="tag">${t.type==='income'?'収入':'支出'}</span>${t.receiptData?'<span class="tag">レシート</span>':''}</div><div class="list-sub">${t.date} / ${escapeHtml(t.category||'その他')} / ${t.cardId?escapeHtml(card(t.cardId)?.name||'カード'):escapeHtml(account(t.accountId)?.name||'')}</div></div><div class="list-value"><b class="${t.type==='income'?'positive':'negative'}">${t.type==='income'?'+':'−'}${yen(t.amount)}</b><div class="item-actions"><button class="mini-link" data-repeat-transaction="${t.id}">再入力</button><button class="mini-link" data-edit-transaction="${t.id}">編集</button><button class="mini-link danger" data-delete-transaction="${t.id}">削除</button></div></div></div>`).join(''):'<div class="empty">この月の収支はありません</div>'}
function renderFutureBalance(){const horizon=num($('forecastHorizon').value||state.settings.forecastHorizon,60);state.settings.forecastHorizon=horizon;const events=cashflowEvents(todayKey(),dateKey(addDays(new Date(),horizon)));let bal=spendableAssets(),rows=[];for(const e of events){bal+=e.amount;rows.push({e,bal})}$('futureBalance').innerHTML=rows.slice(0,30).map(x=>timelineHtml(x.e,x.bal)).join('')||'<div class="empty">将来予定はありません</div>';const points=[];bal=spendableAssets();for(let i=0;i<=horizon;i+=Math.max(1,Math.ceil(horizon/30))){const d=dateKey(addDays(new Date(),i)),p=cashflowEvents(todayKey(),d);points.push(bal+p.reduce((s,e)=>s+e.amount,0))}const min=Math.min(...points,0),max=Math.max(...points,1),span=Math.max(1,max-min);$('futureBalanceChart').innerHTML=points.map(v=>`<div class="spark-bar ${v<num(state.settings.balanceFloor)?'negative':''}" style="height:${Math.max(4,(v-min)/span*100)}%" title="${yen(v)}"></div>`).join('')}
function renderPayslips(){$('payslipList').innerHTML=state.payslips.length?[...state.payslips].sort((a,b)=>b.payDate.localeCompare(a.payDate)).map(p=>{const w=workplace(p.workplaceId),c=cycleByPayDate(w,p.payDate),pred=c?cycleStats(w.id,c).forecast:0,diff=num(p.net)-pred,hours=c?cycleStats(w.id,c).hours:0,eff=hours?num(p.net)/hours:0;return `<div class="list-item"><div class="list-main"><div class="list-title">${escapeHtml(w.name)} ${formatDateJP(p.payDate)}</div><div class="list-sub">総支給 ${yen(p.gross)} / 手取り ${yen(p.net)} / 控除 ${yen(num(p.tax)+num(p.insurance)+num(p.other))} / 実質時給 ${yen(eff)}/h<br>予測 ${yen(pred)} → 差額 ${diff>=0?'+':''}${yen(diff)}</div></div><div class="list-value"><button class="mini-link" data-edit-payslip="${p.id}">編集</button><button class="mini-link danger" data-delete-payslip="${p.id}">削除</button></div></div>`}).join(''):'<div class="empty">給与明細を登録すると予測との差額・実質時給を確認できます</div>'}

function renderAnalysis(){const months=Array.from({length:6},(_,i)=>addMonths(new Date(new Date().getFullYear(),new Date().getMonth(),1,12),i-5));renderBarChart('salaryChart',months.map(m=>shiftsInMonth(m,'all').reduce((s,x)=>s+calculateShift(x).pay,0)),months,'money');renderBarChart('hoursChart',months.map(m=>sumShifts(shiftsInMonth(m,'all')).hours),months,'hours');renderBarChart('spendingChart',months.map(m=>expenseTransactionsInMonth(m).reduce((s,x)=>s+num(x.amount),0)),months,'money');
 const now=new Date(),start90=dateKey(addDays(now,-90));$('workplaceAnalysis').innerHTML=state.workplaces.map(w=>{const l=state.shifts.filter(s=>s.workplaceId===w.id&&s.date>=start90&&s.date<=todayKey()),s=sumShifts(l),eff=s.hours?s.pay/s.hours:wageForDate(w.id,todayKey());return `<div class="list-item"><div class="list-main"><div class="list-title"><span class="color-dot" style="--dot-color:${safeColor(w.color)}"></span>${escapeHtml(w.name)}</div><div class="list-sub">直近90日 ${l.length}件 / ${hoursText(s.hours)} / 給与 ${yen(s.pay)}</div></div><div class="list-value"><b>${yen(eff)}/h</b><small>実質効率</small></div></div>`}).join('');
 const year=now.getFullYear(),annual=annualScheduledIncome(year),forecast=annualForecastIncome(year);$('annualIncome').textContent=yen(annual);$('annualForecast').textContent=yen(forecast);$('incomeWarnings').innerHTML=(state.settings.incomeWarningLines||[]).map(l=>`<div class="alert-item ${forecast>=l?'warn':'good'}"><b>${yen(l)} ライン</b>${forecast>=l?`予測で ${yen(forecast-l)} 超える見込み`:`あと ${yen(l-forecast)}`}</div>`).join('')||'<div class="empty">設定で任意の年間収入ラインを登録できます</div>';renderReports();}
function renderBarChart(id,vals,months,type){const max=Math.max(...vals,1);$(id).innerHTML=vals.map((v,i)=>`<div class="bar-col"><div class="bar-value">${type==='money'?yen(v):hoursText(v)}</div><div class="bar-well"><div class="bar" style="height:${Math.max(2,v/max*100)}%"></div></div><div class="bar-label">${months[i].getMonth()+1}月</div></div>`).join('')}
function annualScheduledIncome(year){return state.shifts.filter(s=>s.date.startsWith(`${year}-`)).reduce((sum,s)=>sum+calculateShift(s).pay,0)+state.transactions.filter(t=>t.type==='income'&&t.date.startsWith(`${year}-`)).reduce((sum,t)=>sum+num(t.amount),0)}
function annualForecastIncome(year){const now=new Date(),done=Math.max(1,now.getMonth()+1),annual=annualScheduledIncome(year),avg=annual/done;return Math.round(avg*12)}
function renderReports(){const d=new Date(),ms=currentMonthStats('all'),ex=expenseTransactionsInMonth(d).reduce((s,x)=>s+num(x.amount),0),inc=incomeTransactionsInMonth(d).reduce((s,x)=>s+num(x.amount),0),fixed=fixedMonthTotal(d),prev=addMonths(new Date(d.getFullYear(),d.getMonth(),1,12),-1),prevPay=shiftsInMonth(prev,'all').reduce((s,x)=>s+calculateShift(x).pay,0),diff=prevPay?((ms.forecast-prevPay)/prevPay*100):0;$('monthlyReport').innerHTML=reportCells([['予定給与',yen(ms.forecast)],['今日まで',yen(ms.current)],['勤務時間',hoursText(ms.hours)],['変動支出',yen(ex)],['固定費',yen(fixed)],['前月比',`${diff>=0?'+':''}${diff.toFixed(1)}%`]]);const year=d.getFullYear(),ys=state.shifts.filter(s=>s.date.startsWith(`${year}-`)),sum=sumShifts(ys),yearEx=state.transactions.filter(t=>t.type==='expense'&&t.date.startsWith(`${year}-`)).reduce((s,x)=>s+num(x.amount),0),best=Array.from({length:12},(_,m)=>({m,p:shiftsInMonth(new Date(year,m,1,12),'all').reduce((s,x)=>s+calculateShift(x).pay,0)})).sort((a,b)=>b.p-a.p)[0];$('annualReport').innerHTML=reportCells([['総給与',yen(sum.pay)],['総勤務',hoursText(sum.hours)],['総支出',yen(yearEx)],['平均月収',yen(sum.pay/(d.getMonth()+1))],['最高月',`${best.m+1}月 ${yen(best.p)}`],['シフト数',`${ys.length}件`]])}
function reportCells(items){return items.map(([a,b])=>`<div class="report-cell"><span>${a}</span><b>${b}</b></div>`).join('')}

function renderSettings(){$('salaryGoal').value=num(state.settings.salaryGoal);$('balanceFloor').value=num(state.settings.balanceFloor);$('incomeWarningLines').value=(state.settings.incomeWarningLines||[]).join(',');$('themeSelect').value=state.settings.theme||'system';$('accentSelect').value=state.settings.accent||'blue';renderDashboardCardSettings();$('workplaceList').innerHTML=state.workplaces.map(w=>`<div class="list-item"><div class="list-main"><div class="list-title"><span class="color-dot" style="--dot-color:${safeColor(w.color)}"></span>${escapeHtml(w.name)} ${w.id===state.settings.selectedWorkplaceId?'<span class="tag">ホーム</span>':''}</div><div class="list-sub">${w.closingDay==='end'?'月末':w.closingDay+'日'}締め / ${w.payLag===0?'当月':w.payLag===1?'翌月':'翌々月'}${w.payDay==='end'?'月末':w.payDay+'日'}払い / ${w.roundingMode==='none'?'1分':w.roundingMinutes+'分'}単位</div></div><div class="list-value"><div class="item-actions"><button class="mini-link" data-select-workplace="${w.id}">表示</button><button class="mini-link" data-edit-workplace="${w.id}">編集</button><button class="mini-link danger" data-delete-workplace="${w.id}">削除</button></div></div></div>`).join('');$('wageHistoryList').innerHTML=state.wageHistory.sort((a,b)=>b.effectiveFrom.localeCompare(a.effectiveFrom)).map(w=>`<div class="list-item"><div class="list-main"><div class="list-title">${escapeHtml(workplace(w.workplaceId).name)} ${yen(w.hourlyWage)}/h</div><div class="list-sub">${w.effectiveFrom} から適用</div></div><div class="list-value"><button class="mini-link" data-edit-wage="${w.id}">編集</button><button class="mini-link danger" data-delete-wage="${w.id}">削除</button></div></div>`).join('')||'<div class="empty">時給履歴なし</div>';$('presetList').innerHTML=state.presets.map(p=>{const c=calculatePreset(p);return `<div class="list-item"><div class="list-main"><div class="list-title"><span class="color-dot" style="--dot-color:${safeColor(p.color,workplace(p.workplaceId).color)}"></span>${escapeHtml(p.name)} <span class="tag">${escapeHtml(workplace(p.workplaceId).name)}</span></div><div class="list-sub">${p.start}–${p.end} / 休憩${p.useAutoBreak?'自動':num(p.breakMinutes)+'分'} / 約${yen(c.pay)}</div></div><div class="list-value"><button class="mini-link" data-edit-preset="${p.id}">編集</button><button class="mini-link danger" data-delete-preset="${p.id}">削除</button></div></div>`}).join('')||'<div class="empty">プリセットなし</div>';try{const b=JSON.parse(localStorage.getItem(BACKUP_KEY)||'null');$('backupTimestamp').textContent=b?.at?new Date(b.at).toLocaleString('ja-JP'):'—'}catch{$('backupTimestamp').textContent='—'}}
function renderDashboardCardSettings(){$('dashboardCardSettings').innerHTML=state.settings.dashboardOrder.map((id,i)=>`<div class="list-item dashboard-setting-row"><input type="checkbox" data-card-toggle="${id}" ${state.settings.dashboardHidden.includes(id)?'':'checked'} /><span>${CARD_LABELS[id]}</span><button type="button" data-card-up="${id}" ${i===0?'disabled':''}>↑</button><button type="button" data-card-down="${id}" ${i===state.settings.dashboardOrder.length-1?'disabled':''}>↓</button></div>`).join('')}
function renderAll(){renderSelects();renderDashboard();renderShifts();renderBudget();renderAnalysis();renderSettings()}

function navigate(p){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.dataset.page===p));document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.nav===p));location.hash=p;window.scrollTo({top:0,behavior:'smooth'});if(p==='budget')renderBudget();if(p==='analysis')renderAnalysis()}
function openDialog(id){const d=$(id);if(d&&!d.open)d.showModal()}
function closeDialogs(){document.querySelectorAll('dialog[open]').forEach(d=>d.close())}
function openWorkplaceEditor(id=''){const w=id?state.workplaces.find(x=>x.id===id):createDefaultWorkplace();$('workplaceId').value=id;$('workplaceModalTitle').textContent=id?'勤務先を編集':'勤務先を追加';for(const [el,key] of [['workplaceName','name'],['workplaceColor','color'],['closingDay','closingDay'],['payDay','payDay'],['payLag','payLag'],['weekendRule','weekendRule'],['roundingMode','roundingMode'],['roundingMinutes','roundingMinutes'],['autoBreak6','autoBreak6'],['autoBreak8','autoBreak8'],['transportMode','transportMode'],['transportPerShift','transportPerShift'],['transportPerKm','transportPerKm'],['transportMonthlyCap','transportMonthlyCap'],['shiftAllowance','shiftAllowance'],['weekendAllowance','weekendAllowance'],['overtimeAfterHours','overtimeAfterHours'],['overtimeRate','overtimeRate'],['nightStart','nightStart'],['nightEnd','nightEnd'],['nightRate','nightRate'],['earlyStart','earlyStart'],['earlyEnd','earlyEnd'],['earlyRate','earlyRate']])$(el).value=w[key]??'';openDialog('workplaceModal')}
function openWageEditor(id=''){const w=id?state.wageHistory.find(x=>x.id===id):null;$('wageId').value=w?.id||'';$('wageWorkplace').value=w?.workplaceId||state.settings.selectedWorkplaceId;$('wageEffectiveFrom').value=w?.effectiveFrom||todayKey();$('wageAmount').value=w?.hourlyWage??'';$('wageModalTitle').textContent=w?'時給を編集':'時給を追加';openDialog('wageModal')}
function openPresetEditor(id=''){const p=id?state.presets.find(x=>x.id===id):null;$('presetId').value=p?.id||'';$('presetWorkplace').value=p?.workplaceId||state.settings.selectedWorkplaceId;$('presetName').value=p?.name||'';$('presetStart').value=p?.start||'17:00';$('presetEnd').value=p?.end||'21:00';$('presetBreak').value=p?.breakMinutes??0;$('presetAutoBreak').checked=!!p?.useAutoBreak;$('presetTransport').value=p?.transportOverride??'';$('presetColor').value=safeColor(p?.color,workplace(p?.workplaceId||state.settings.selectedWorkplaceId).color);$('presetModalTitle').textContent=p?'プリセット編集':'プリセット作成';openDialog('presetModal')}
function openShiftEditor(id='',date=todayKey(),presetId=''){const s=id?state.shifts.find(x=>x.id===id):null;$('shiftId').value=s?.id||'';$('shiftWorkplace').value=s?.workplaceId||preset(presetId)?.workplaceId||state.settings.selectedWorkplaceId;renderPresetSelects();$('shiftDate').value=s?.date||date;$('shiftPreset').value=s?.presetId||presetId||'';$('shiftStart').value=s?.planned?.start||'';$('shiftEnd').value=s?.planned?.end||'';$('shiftBreak').value=s?.planned?.breakMinutes??0;$('shiftAutoBreak').checked=!!s?.useAutoBreak;$('shiftWageOverride').value=s?.wageOverride??'';$('shiftTransportOverride').value=s?.transportOverride??'';$('shiftDistanceKm').value=s?.distanceKm??'';$('shiftNote').value=s?.note||'';$('shiftModalTitle').textContent=s?'シフト編集':'シフト追加';if(!s&&presetId)applyPresetToShift(presetId);updateShiftPreview();openDialog('shiftModal')}
function applyPresetToShift(id){const p=preset(id);if(!p)return;$('shiftWorkplace').value=p.workplaceId;renderPresetSelects();$('shiftPreset').value=id;$('shiftStart').value=p.start;$('shiftEnd').value=p.end;$('shiftBreak').value=p.breakMinutes??0;$('shiftAutoBreak').checked=!!p.useAutoBreak;$('shiftTransportOverride').value=p.transportOverride??'';updateShiftPreview()}
function buildShiftFromForm(){return {id:$('shiftId').value||uid(),workplaceId:$('shiftWorkplace').value,date:$('shiftDate').value,planned:{start:$('shiftStart').value,end:$('shiftEnd').value,breakMinutes:num($('shiftBreak').value)},useAutoBreak:$('shiftAutoBreak').checked,presetId:$('shiftPreset').value||'',wageOverride:$('shiftWageOverride').value===''?null:num($('shiftWageOverride').value),transportOverride:$('shiftTransportOverride').value===''?null:num($('shiftTransportOverride').value),distanceKm:num($('shiftDistanceKm').value),note:$('shiftNote').value.trim()}}
function updateShiftPreview(){try{$('shiftPayPreview').textContent=yen(calculateShift(buildShiftFromForm()).pay)}catch{$('shiftPayPreview').textContent='¥0'}}
function openTransactionEditor(type='expense',id='',copy=false){let t=id?state.transactions.find(x=>x.id===id):null;if(copy&&t)t={...t,id:'',date:todayKey()};$('transactionId').value=t?.id||'';$('transactionType').value=t?.type||type;$('transactionModalTitle').textContent=(t?.type||type)==='income'?'収入を追加':'支出を追加';$('transactionDate').value=t?.date||todayKey();$('transactionName').value=t?.name||'';$('transactionAmount').value=t?.amount??'';$('transactionCategory').value=t?.category||((t?.type||type)==='income'?'臨時収入':'その他');$('transactionAccount').value=t?.accountId||state.accounts[0]?.id||'';$('transactionCard').value=t?.cardId||'';$('transactionNote').value=t?.note||'';tempReceiptData=t?.receiptData||'';renderReceiptPreview();openDialog('transactionModal')}
function renderReceiptPreview(){$('receiptPreview').innerHTML=tempReceiptData?`<img src="${tempReceiptData}" alt="レシート写真" />`:''}
function openFixedEditor(id=''){const f=id?state.fixedCosts.find(x=>x.id===id):null;$('fixedId').value=f?.id||'';$('fixedName').value=f?.name||'';$('fixedAmount').value=f?fixedAmountOn(f,todayKey()):'';$('fixedPriceFrom').value=todayKey();$('fixedCategory').value=f?.category||'サブスク';$('fixedSubscription').checked=f?.isSubscription!==false;$('fixedRecurrence').value=f?.recurrence||'monthly';$('fixedMonth').value=f?.month||'1';$('fixedDay').value=f?.day||'1';$('fixedEnabled').checked=f?.enabled!==false;$('fixedAccount').value=f?.accountId||state.accounts[0]?.id||'';$('fixedCard').value=f?.cardId||'';$('fixedModalTitle').textContent=f?'固定費を編集':'固定費を登録';toggleFixedMonth();openDialog('fixedModal')}
function toggleFixedMonth(){$('fixedMonthWrap').hidden=$('fixedRecurrence').value!=='yearly'}
function openBudgetEditor(cat=''){const b=state.categoryBudgets.find(x=>x.category===cat);$('budgetCategory').value=b?.category||cat;$('budgetAmount').value=b?.amount??'';openDialog('budgetModal')}
function openPayslipEditor(id=''){const p=id?state.payslips.find(x=>x.id===id):null;$('payslipId').value=p?.id||'';$('payslipWorkplace').value=p?.workplaceId||state.settings.selectedWorkplaceId;$('payslipPayDate').value=p?.payDate||nextPayCycle(workplace(state.settings.selectedWorkplaceId)).payDate;$('payslipGross').value=p?.gross??'';$('payslipNet').value=p?.net??'';$('payslipTax').value=p?.tax??0;$('payslipInsurance').value=p?.insurance??0;$('payslipOther').value=p?.other??0;$('payslipNote').value=p?.note||'';openDialog('payslipModal')}

function promptAccount(id=''){const a=id?state.accounts.find(x=>x.id===id):null,name=prompt('口座・財布名',a?.name||'');if(!name)return;const type=prompt('種類: bank / cash / emoney',a?.type||'bank')||'bank',balance=num(prompt('現在残高',a?.balance??0)),isSavings=confirm('この口座を「貯金」として扱いますか？');const item={id:a?.id||uid(),name,type:['bank','cash','emoney'].includes(type)?type:'bank',balance,isSavings};const i=state.accounts.findIndex(x=>x.id===item.id);if(i>=0)state.accounts[i]=item;else state.accounts.push(item);persist()}
function promptTransfer(){if(state.accounts.length<2){toast('口座を2つ以上登録してください');return}const from=prompt(`振替元の名前\n${state.accounts.map(a=>a.name).join(' / ')}`,state.accounts[0].name),to=prompt('振替先の名前',state.accounts[1].name),a=state.accounts.find(x=>x.name===from),b=state.accounts.find(x=>x.name===to);if(!a||!b||a.id===b.id)return;const amount=num(prompt('振替金額',1000));if(amount<=0)return;a.balance-=amount;b.balance+=amount;state.transactions.push({id:uid(),date:todayKey(),type:'transfer',name:`${a.name} → ${b.name}`,amount,category:'振替',accountId:a.id,toAccountId:b.id,cardId:'',note:'',receiptData:''});persist();toast('振替しました')}
function promptCard(id=''){const c=id?state.cards.find(x=>x.id===id):null,name=prompt('カード名',c?.name||'');if(!name)return;const closing=prompt('締め日（1〜31 または end）',c?.closingDay||'end')||'end',pay=prompt('支払日（1〜31 または end）',c?.payDay||'27')||'27',lag=num(prompt('支払い月: 締め月=0 / 翌月=1 / 翌々月=2',c?.payLag??1),1),accName=prompt(`引落口座名\n${state.accounts.map(a=>a.name).join(' / ')}`,account(c?.accountId).name),acc=state.accounts.find(a=>a.name===accName)||state.accounts[0],item={id:c?.id||uid(),name,closingDay:closing,payDay:pay,payLag:lag,accountId:acc.id};const i=state.cards.findIndex(x=>x.id===item.id);if(i>=0)state.cards[i]=item;else state.cards.push(item);persist()}
function promptGoal(id=''){const g=id?state.savingGoals.find(x=>x.id===id):null,name=prompt('目標名',g?.name||'');if(!name)return;const target=num(prompt('目標金額',g?.target??100000)),current=num(prompt('現在貯まっている額',g?.current??0)),monthly=num(prompt('毎月積立予定（0なら収支平均から予測）',g?.monthlyContribution??0)),item={id:g?.id||uid(),name,target,current,monthlyContribution:monthly};const i=state.savingGoals.findIndex(x=>x.id===item.id);if(i>=0)state.savingGoals[i]=item;else state.savingGoals.push(item);persist()}
function promptExpenseTemplate(){const name=prompt('テンプレート名（例：ラーメン）','');if(!name)return;const amount=num(prompt('金額',1000)),category=prompt('カテゴリ','食費')||'その他';state.expenseTemplates.push({id:uid(),name,amount,category,accountId:state.accounts[0]?.id||''});persist()}
function useExpenseTemplate(id){const t=state.expenseTemplates.find(x=>x.id===id);if(!t)return;state.transactions.push({id:uid(),date:todayKey(),type:'expense',name:t.name,amount:num(t.amount),category:t.category,accountId:t.accountId||state.accounts[0]?.id||'',toAccountId:'',cardId:'',note:'テンプレートから追加',receiptData:''});persist();toast(`${t.name} ${yen(t.amount)} を追加しました`)}

function copyShift(id,weeks=1){const s=state.shifts.find(x=>x.id===id);if(!s)return;for(let i=1;i<=weeks;i++)state.shifts.push({...structuredClone(s),id:uid(),date:dateKey(addDays(parseDate(s.date),7*i))});persist();toast(`${weeks}週分コピーしました`)}
function copyPreviousMonth(){const target=shiftViewMonth,prev=addMonths(target,-1),source=shiftsInMonth(prev,$('shiftWorkplaceFilter').value||'all');if(!source.length){toast('前月にシフトがありません');return}if(!confirm(`${source.length}件を今月へコピーしますか？`))return;for(const s of source){const d=parseDate(s.date),day=Math.min(d.getDate(),daysInMonth(target.getFullYear(),target.getMonth()));state.shifts.push({...structuredClone(s),id:uid(),date:dateKey(new Date(target.getFullYear(),target.getMonth(),day,12))})}persist();toast(`${source.length}件コピーしました`)}
function buildSuggestions(){const wp=workplace(state.settings.selectedWorkplaceId),c=nextPayCycle(wp),gp=preset(state.settings.goalPresetId);if(!gp){toast('目標用プリセットを設定してください');return}const st=cycleStats(wp.id,c),remain=Math.max(0,num(state.settings.salaryGoal)-st.forecast),pc=calculatePreset(gp,c.end),need=pc.pay?Math.ceil(remain/pc.pay):0;if(need<=0){toast('目標は達成済みです');return}const start=addDays(new Date(),1),end=parseDate(c.end),cand=[];for(let d=new Date(start);d<=end&&cand.length<need;d=addDays(d,1)){const k=dateKey(d),has=state.shifts.some(s=>s.workplaceId===wp.id&&s.date===k);if(!has)cand.push(k)}suggestedDates=cand;$('suggestionSummary').innerHTML=`不足 ${yen(remain)} / 「${escapeHtml(gp.name)}」ならあと ${need}回。空いている日から ${cand.length}日を候補にしました。`;$('suggestionDates').innerHTML=cand.map(d=>`<button type="button" class="date-select-chip selected" data-suggest-date="${d}">${shortDate(d)}</button>`).join('');$('addSuggestedShiftsBtn').disabled=!cand.length;openDialog('suggestionModal')}
function addSuggested(){const gp=preset(state.settings.goalPresetId);if(!gp)return;for(const d of suggestedDates)state.shifts.push({id:uid(),workplaceId:gp.workplaceId,date:d,planned:{start:gp.start,end:gp.end,breakMinutes:gp.breakMinutes??0},useAutoBreak:!!gp.useAutoBreak,presetId:gp.id,wageOverride:null,transportOverride:gp.transportOverride,distanceKm:0,note:`${gp.name}（目標候補）`});suggestedDates=[];persist();closeDialogs();toast('候補シフトを追加しました')}

function simulatePurchase(){const name=$('purchaseName').value.trim()||'この買い物',price=num($('purchasePrice').value),wp=workplace(state.settings.selectedWorkplaceId),gp=preset(state.settings.goalPresetId),pc=gp?calculatePreset(gp):{pay:0,hours:0},wage=wageForDate(wp.id,todayKey()),hours=wage?price/wage:0,shifts=pc.pay?Math.ceil(price/pc.pay):0,after=spendableAssets()-price,future30=cashflowEvents(todayKey(),dateKey(addDays(new Date(),30))).reduce((s,e)=>s+e.amount,0),safe=after+future30>=num(state.settings.balanceFloor);$('purchaseResult').innerHTML=`<b>${escapeHtml(name)} ${yen(price)}</b><br>労働時間換算：約 ${hoursText(hours)}${gp?` / 「${escapeHtml(gp.name)}」約 ${shifts}回`:''}<br>購入直後の自由資金：${yen(after)}<br>30日以内の予定反映後：${yen(after+future30)}<br><strong class="${safe?'positive':'negative'}">${safe?'現在の設定上は最低残高を維持できます':'最低残高ラインを割る見込みです'}</strong>`}
function renderSearch(q=''){const query=q.trim().toLowerCase();if(!query){$('searchResults').innerHTML='<div class="empty">キーワードを入力してください</div>';return}const rows=[];for(const s of state.shifts){const text=`${s.date} ${workplace(s.workplaceId).name} ${s.note}`.toLowerCase();if(text.includes(query))rows.push({title:`シフト ${s.date} ${workplace(s.workplaceId).name}`,sub:`${s.planned.start}–${s.planned.end} / ${yen(calculateShift(s).pay)}`})}for(const t of state.transactions){const text=`${t.date} ${t.name} ${t.category} ${t.note}`.toLowerCase();if(text.includes(query))rows.push({title:`${t.type==='income'?'収入':'支出'} ${t.name}`,sub:`${t.date} / ${yen(t.amount)} / ${t.category}`})}for(const f of state.fixedCosts)if(`${f.name} ${f.category}`.toLowerCase().includes(query))rows.push({title:`固定費 ${f.name}`,sub:`${yen(fixedAmountOn(f,todayKey()))} / ${f.category}`});for(const p of state.payslips)if(`${workplace(p.workplaceId).name} ${p.payDate}`.toLowerCase().includes(query))rows.push({title:`給与明細 ${workplace(p.workplaceId).name}`,sub:`${p.payDate} / 手取り ${yen(p.net)}`});$('searchResults').innerHTML=rows.slice(0,50).map(r=>`<div class="list-item"><div class="list-main"><div class="list-title">${escapeHtml(r.title)}</div><div class="list-sub">${escapeHtml(r.sub)}</div></div></div>`).join('')||'<div class="empty">見つかりませんでした</div>'}
function resizeReceipt(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>{const img=new Image();img.onload=()=>{const max=700,scale=Math.min(1,max/img.width),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.72))};img.onerror=reject;img.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
function exportJSON(){downloadBlob(`shiftwallet-${todayKey()}.json`,JSON.stringify(state,null,2),'application/json')}
function exportCSV(){const esc=v=>`"${String(v??'').replaceAll('"','""')}"`;let lines=['type,date,workplace,name,start,end,break_minutes,hours,amount,category,note'];for(const s of state.shifts){const c=calculateShift(s);lines.push(['shift',s.date,workplace(s.workplaceId).name,s.note,s.planned.start,s.planned.end,c.breakMinutes,c.hours,c.pay,'',s.note].map(esc).join(','))}for(const t of state.transactions)lines.push(['transaction',t.date,'',t.name,'','','','',t.type==='income'?t.amount:-t.amount,t.category,t.note].map(esc).join(','));downloadBlob(`shiftwallet-${todayKey()}.csv`,`\ufeff${lines.join('\n')}`,'text/csv;charset=utf-8')}

function bindForms(){
 $('moneySettingsForm').addEventListener('submit',e=>{e.preventDefault();state.settings.salaryGoal=num($('salaryGoal').value);state.settings.balanceFloor=num($('balanceFloor').value);state.settings.goalPresetId=$('goalPreset').value;state.settings.incomeWarningLines=$('incomeWarningLines').value.split(',').map(Number).filter(x=>x>0).sort((a,b)=>a-b);persist();toast('設定を保存しました')});
 $('workplaceForm').addEventListener('submit',e=>{e.preventDefault();const id=$('workplaceId').value||uid(),old=state.workplaces.find(x=>x.id===id)||{},item={...createDefaultWorkplace(),...old,id,name:$('workplaceName').value.trim(),color:safeColor($('workplaceColor').value),closingDay:$('closingDay').value,payDay:$('payDay').value,payLag:num($('payLag').value),weekendRule:$('weekendRule').value,roundingMode:$('roundingMode').value,roundingMinutes:num($('roundingMinutes').value,1),autoBreak6:num($('autoBreak6').value),autoBreak8:num($('autoBreak8').value),transportMode:$('transportMode').value,transportPerShift:num($('transportPerShift').value),transportPerKm:num($('transportPerKm').value),transportMonthlyCap:num($('transportMonthlyCap').value),shiftAllowance:num($('shiftAllowance').value),weekendAllowance:num($('weekendAllowance').value),overtimeAfterHours:num($('overtimeAfterHours').value,8),overtimeRate:num($('overtimeRate').value,1.25),nightStart:$('nightStart').value,nightEnd:$('nightEnd').value,nightRate:num($('nightRate').value,1.25),earlyStart:$('earlyStart').value,earlyEnd:$('earlyEnd').value,earlyRate:num($('earlyRate').value,1)};const i=state.workplaces.findIndex(x=>x.id===id);if(i>=0)state.workplaces[i]=item;else{state.workplaces.push(item);state.wageHistory.push({id:uid(),workplaceId:id,effectiveFrom:todayKey(),hourlyWage:0})}persist();closeDialogs();toast('勤務先を保存しました')});
 $('wageForm').addEventListener('submit',e=>{e.preventDefault();const id=$('wageId').value||uid(),item={id,workplaceId:$('wageWorkplace').value,effectiveFrom:$('wageEffectiveFrom').value,hourlyWage:num($('wageAmount').value)},i=state.wageHistory.findIndex(x=>x.id===id);if(i>=0)state.wageHistory[i]=item;else state.wageHistory.push(item);persist();closeDialogs();toast('時給を保存しました')});
 $('presetForm').addEventListener('submit',e=>{e.preventDefault();const id=$('presetId').value||uid(),item={id,workplaceId:$('presetWorkplace').value,name:$('presetName').value.trim(),start:$('presetStart').value,end:$('presetEnd').value,breakMinutes:num($('presetBreak').value),useAutoBreak:$('presetAutoBreak').checked,transportOverride:$('presetTransport').value===''?null:num($('presetTransport').value),color:safeColor($('presetColor').value,workplace($('presetWorkplace').value).color)},i=state.presets.findIndex(x=>x.id===id);if(i>=0)state.presets[i]=item;else state.presets.push(item);if(!state.settings.goalPresetId)state.settings.goalPresetId=id;persist();closeDialogs();toast(`プリセットを保存しました（休憩 ${item.useAutoBreak?'自動':item.breakMinutes+'分'}）`)});
 $('shiftForm').addEventListener('submit',e=>{e.preventDefault();const item=buildShiftFromForm(),i=state.shifts.findIndex(x=>x.id===item.id);if(i>=0)state.shifts[i]=item;else state.shifts.push(item);persist();closeDialogs();toast('シフトを保存しました')});
 $('bulkShiftForm').addEventListener('submit',e=>{e.preventDefault();const p=preset($('bulkPreset').value);if(!p||!bulkSelectedDates.size)return;for(const d of [...bulkSelectedDates].sort())state.shifts.push({id:uid(),workplaceId:p.workplaceId,date:d,planned:{start:p.start,end:p.end,breakMinutes:p.breakMinutes??0},useAutoBreak:!!p.useAutoBreak,presetId:p.id,wageOverride:null,transportOverride:p.transportOverride,distanceKm:0,note:p.name});const n=bulkSelectedDates.size;bulkSelectedDates.clear();persist();closeDialogs();toast(`${n}件追加しました`)});
 $('transactionForm').addEventListener('submit',e=>{e.preventDefault();const id=$('transactionId').value||uid(),item={id,date:$('transactionDate').value,type:$('transactionType').value,name:$('transactionName').value.trim(),amount:num($('transactionAmount').value),category:$('transactionCategory').value.trim()||'その他',accountId:$('transactionAccount').value,toAccountId:'',cardId:itemTypeCard(),note:$('transactionNote').value.trim(),receiptData:tempReceiptData};const i=state.transactions.findIndex(x=>x.id===id);if(i>=0)state.transactions[i]=item;else state.transactions.push(item);persist();closeDialogs();tempReceiptData='';toast('収支を保存しました')});
 $('fixedForm').addEventListener('submit',e=>{e.preventDefault();const id=$('fixedId').value||uid(),old=state.fixedCosts.find(x=>x.id===id),amount=num($('fixedAmount').value),from=$('fixedPriceFrom').value||todayKey(),hist=old?.priceHistory?[...old.priceHistory]:[];if(!hist.length||num(hist.at(-1)?.amount)!==amount||hist.at(-1)?.from!==from){hist.push({from,amount});hist.sort((a,b)=>a.from.localeCompare(b.from))}const item={id,name:$('fixedName').value.trim(),amount,category:$('fixedCategory').value.trim()||'固定費',isSubscription:$('fixedSubscription').checked,recurrence:$('fixedRecurrence').value,month:$('fixedRecurrence').value==='yearly'?num($('fixedMonth').value):null,day:$('fixedDay').value,enabled:$('fixedEnabled').checked,accountId:$('fixedAccount').value,cardId:$('fixedCard').value,priceHistory:hist},i=state.fixedCosts.findIndex(x=>x.id===id);if(i>=0)state.fixedCosts[i]=item;else state.fixedCosts.push(item);persist();closeDialogs();toast('固定費を保存しました')});
 $('budgetForm').addEventListener('submit',e=>{e.preventDefault();const cat=$('budgetCategory').value.trim(),amount=num($('budgetAmount').value),i=state.categoryBudgets.findIndex(x=>x.category===cat);if(i>=0)state.categoryBudgets[i]={category:cat,amount};else state.categoryBudgets.push({category:cat,amount});persist();closeDialogs();toast('予算を保存しました')});
 $('payslipForm').addEventListener('submit',e=>{e.preventDefault();const id=$('payslipId').value||uid(),item={id,workplaceId:$('payslipWorkplace').value,payDate:$('payslipPayDate').value,gross:num($('payslipGross').value),net:num($('payslipNet').value),tax:num($('payslipTax').value),insurance:num($('payslipInsurance').value),other:num($('payslipOther').value),note:$('payslipNote').value.trim()},i=state.payslips.findIndex(x=>x.id===id);if(i>=0)state.payslips[i]=item;else state.payslips.push(item);persist();closeDialogs();toast('給与明細を保存しました')});
}
function itemTypeCard(){return $('transactionType').value==='expense'?$('transactionCard').value:''}
function bindEvents(){
 document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>navigate(b.dataset.nav));document.querySelectorAll('[data-nav-to]').forEach(b=>b.onclick=()=>navigate(b.dataset.navTo));document.querySelectorAll('[data-close-dialog]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
 $('dashboardWorkplace').onchange=()=>{state.settings.selectedWorkplaceId=$('dashboardWorkplace').value;const p=state.presets.find(x=>x.workplaceId===state.settings.selectedWorkplaceId);state.settings.goalPresetId=p?.id||'';persist()};$('shiftWorkplaceFilter').onchange=renderShifts;$('prevMonth').onclick=()=>{shiftViewMonth=addMonths(shiftViewMonth,-1);renderShifts()};$('nextMonth').onclick=()=>{shiftViewMonth=addMonths(shiftViewMonth,1);renderShifts()};$('prevBudgetMonth').onclick=()=>{budgetViewMonth=addMonths(budgetViewMonth,-1);renderBudget()};$('nextBudgetMonth').onclick=()=>{budgetViewMonth=addMonths(budgetViewMonth,1);renderBudget()};
 $('openWorkplaceModal').onclick=()=>openWorkplaceEditor();$('openWageModal').onclick=()=>openWageEditor();$('openPresetModal').onclick=()=>openPresetEditor();$('openShiftModal').onclick=()=>openShiftEditor();$('openBulkShiftModal').onclick=openBulkShiftPicker;$('openFixedModal').onclick=()=>openFixedEditor();$('openExpenseModal').onclick=()=>openTransactionEditor('expense');$('openIncomeModal').onclick=()=>openTransactionEditor('income');$('openBudgetModal').onclick=()=>openBudgetEditor();$('openPayslipModal').onclick=()=>openPayslipEditor();
 $('shiftWorkplace').onchange=()=>{renderPresetSelects();updateShiftPreview()};$('shiftPreset').onchange=()=>{if($('shiftPreset').value)applyPresetToShift($('shiftPreset').value)};for(const id of ['shiftDate','shiftStart','shiftEnd','shiftBreak','shiftAutoBreak','shiftWageOverride','shiftTransportOverride','shiftDistanceKm'])$(id).addEventListener('input',updateShiftPreview);$('bulkWorkplace').onchange=()=>{renderPresetSelects();renderBulkCalendar()};$('bulkPreset').onchange=renderBulkCalendar;$('fixedRecurrence').onchange=toggleFixedMonth;$('forecastHorizon').onchange=()=>{state.settings.forecastHorizon=num($('forecastHorizon').value);persist(false);renderFutureBalance()};
 $('calendarGrid').onclick=e=>{const c=e.target.closest('[data-calendar-date]');if(c)openDayShift(c.dataset.calendarDate)};$('dayAddShiftBtn').onclick=()=>{closeDialogs();openShiftEditor('',selectedDay)};$('bulkCalendarGrid').onclick=e=>{const c=e.target.closest('[data-bulk-date]');if(!c||c.disabled)return;const k=c.dataset.bulkDate;bulkSelectedDates.has(k)?bulkSelectedDates.delete(k):bulkSelectedDates.add(k);renderBulkCalendar()};$('bulkPrevMonth').onclick=()=>{bulkViewMonth=addMonths(bulkViewMonth,-1);renderBulkCalendar()};$('bulkNextMonth').onclick=()=>{bulkViewMonth=addMonths(bulkViewMonth,1);renderBulkCalendar()};$('bulkClearDates').onclick=()=>{bulkSelectedDates.clear();renderBulkCalendar()};$('copyPrevMonthBtn').onclick=copyPreviousMonth;
 $('suggestShiftBtn').onclick=buildSuggestions;$('addSuggestedShiftsBtn').onclick=addSuggested;$('simulatePurchaseBtn').onclick=simulatePurchase;$('addAccountBtn').onclick=()=>promptAccount();$('transferBtn').onclick=promptTransfer;$('addCardBtn').onclick=()=>promptCard();$('addSavingGoalBtn').onclick=()=>promptGoal();$('addExpenseTemplateBtn').onclick=promptExpenseTemplate;
 $('themeSelect').onchange=()=>{state.settings.theme=$('themeSelect').value;persist()};$('accentSelect').onchange=()=>{state.settings.accent=$('accentSelect').value;persist()};$('searchBtn').onclick=()=>{openDialog('searchModal');$('searchInput').focus();renderSearch('')};$('searchInput').oninput=()=>renderSearch($('searchInput').value);
 $('receiptImage').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{tempReceiptData=await resizeReceipt(f);renderReceiptPreview()}catch{toast('画像を読み込めませんでした')}};
 $('exportJsonBtn').onclick=exportJSON;$('exportCsvBtn').onclick=exportCSV;$('importInput').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{state=normalizeState(JSON.parse(await f.text()));persist();toast('バックアップを読み込みました')}catch{toast('JSONを読み込めませんでした')}e.target.value=''};$('restoreAutoBackupBtn').onclick=()=>{try{const b=JSON.parse(localStorage.getItem(BACKUP_KEY)||'null');if(b?.state&&confirm(`${b.date} の自動バックアップを復元しますか？`)){state=normalizeState(b.state);persist();toast('復元しました')}else if(!b?.state)toast('自動バックアップがありません')}catch{toast('復元できませんでした')}};$('resetBtn').onclick=()=>{if(confirm('全データを削除します。自動バックアップも削除します。')){state=defaultState();localStorage.removeItem(BACKUP_KEY);persist();toast('初期化しました')}};
 $('installBtn').onclick=async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;$('installBtn').hidden=true}else navigate('settings')};
 document.body.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const q=n=>b.dataset[n];if(q('quickPreset')){const p=preset(q('quickPreset')),d=$('quickDate').value||todayKey();state.shifts.push({id:uid(),workplaceId:p.workplaceId,date:d,planned:{start:p.start,end:p.end,breakMinutes:p.breakMinutes??0},useAutoBreak:!!p.useAutoBreak,presetId:p.id,wageOverride:null,transportOverride:p.transportOverride,distanceKm:0,note:p.name});persist();toast(`${d} に追加しました`)}if(q('editShift')){closeDialogs();openShiftEditor(q('editShift'))}if(q('deleteShift')&&confirm('このシフトを削除しますか？')){state.shifts=state.shifts.filter(x=>x.id!==q('deleteShift'));persist();if($('dayShiftModal').open)openDayShift(selectedDay)}if(q('copyWeek'))copyShift(q('copyWeek'),1);if(q('copyFour'))copyShift(q('copyFour'),4);
 if(q('editWorkplace'))openWorkplaceEditor(q('editWorkplace'));if(q('selectWorkplace')){state.settings.selectedWorkplaceId=q('selectWorkplace');state.settings.goalPresetId=state.presets.find(x=>x.workplaceId===q('selectWorkplace'))?.id||'';persist()}if(q('deleteWorkplace'))deleteWorkplace(q('deleteWorkplace'));if(q('editWage'))openWageEditor(q('editWage'));if(q('deleteWage')&&confirm('削除しますか？')){state.wageHistory=state.wageHistory.filter(x=>x.id!==q('deleteWage'));persist()}if(q('editPreset'))openPresetEditor(q('editPreset'));if(q('deletePreset')&&confirm('削除しますか？')){state.presets=state.presets.filter(x=>x.id!==q('deletePreset'));persist()}
 if(q('editTransaction'))openTransactionEditor('expense',q('editTransaction'));if(q('repeatTransaction'))openTransactionEditor('expense',q('repeatTransaction'),true);if(q('deleteTransaction')&&confirm('削除しますか？')){state.transactions=state.transactions.filter(x=>x.id!==q('deleteTransaction'));persist()}if(q('useTemplate'))useExpenseTemplate(q('useTemplate'));
 if(q('editFixed'))openFixedEditor(q('editFixed'));if(q('toggleFixed')){const f=state.fixedCosts.find(x=>x.id===q('toggleFixed'));if(f)f.enabled=f.enabled===false;persist()}if(q('deleteFixed')&&confirm('削除しますか？')){state.fixedCosts=state.fixedCosts.filter(x=>x.id!==q('deleteFixed'));persist()}if(q('editBudget'))openBudgetEditor(q('editBudget'));if(q('deleteBudget')&&confirm('削除しますか？')){state.categoryBudgets=state.categoryBudgets.filter(x=>x.category!==q('deleteBudget'));persist()}if(q('editPayslip'))openPayslipEditor(q('editPayslip'));if(q('deletePayslip')&&confirm('削除しますか？')){state.payslips=state.payslips.filter(x=>x.id!==q('deletePayslip'));persist()}
 if(q('editAccount'))promptAccount(q('editAccount'));if(q('deleteAccount'))deleteAccount(q('deleteAccount'));if(q('editCard'))promptCard(q('editCard'));if(q('deleteCard')&&confirm('カードを削除しますか？')){state.cards=state.cards.filter(x=>x.id!==q('deleteCard'));state.transactions.forEach(t=>{if(t.cardId===q('deleteCard'))t.cardId=''});state.fixedCosts.forEach(f=>{if(f.cardId===q('deleteCard'))f.cardId=''});persist()}if(q('editGoal'))promptGoal(q('editGoal'));if(q('deleteGoal')&&confirm('目標を削除しますか？')){state.savingGoals=state.savingGoals.filter(x=>x.id!==q('deleteGoal'));persist()}
 if(q('cardToggle')){const id=q('cardToggle'),hidden=state.settings.dashboardHidden;hidden.includes(id)?state.settings.dashboardHidden=hidden.filter(x=>x!==id):hidden.push(id);persist()}if(q('cardUp'))moveCard(q('cardUp'),-1);if(q('cardDown'))moveCard(q('cardDown'),1);
 if(q('suggestDate')){const d=q('suggestDate');suggestedDates= suggestedDates.includes(d)?suggestedDates.filter(x=>x!==d):[...suggestedDates,d];b.classList.toggle('selected',suggestedDates.includes(d));$('addSuggestedShiftsBtn').disabled=!suggestedDates.length}
 });
}
function moveCard(id,dir){const a=state.settings.dashboardOrder,i=a.indexOf(id),j=i+dir;if(i<0||j<0||j>=a.length)return;[a[i],a[j]]=[a[j],a[i]];persist()}
function deleteWorkplace(id){if(state.workplaces.length<=1){toast('最後の勤務先は削除できません');return}if(!confirm('関連するシフト・プリセット・給与明細・時給履歴も削除します。続けますか？'))return;state.workplaces=state.workplaces.filter(x=>x.id!==id);state.wageHistory=state.wageHistory.filter(x=>x.workplaceId!==id);state.presets=state.presets.filter(x=>x.workplaceId!==id);state.shifts=state.shifts.filter(x=>x.workplaceId!==id);state.payslips=state.payslips.filter(x=>x.workplaceId!==id);if(state.settings.selectedWorkplaceId===id)state.settings.selectedWorkplaceId=state.workplaces[0].id;state.settings.goalPresetId=state.presets.find(x=>x.workplaceId===state.settings.selectedWorkplaceId)?.id||'';persist()}
function deleteAccount(id){if(state.accounts.length<=1){toast('最後の口座は削除できません');return}if(!confirm('口座を削除しますか？関連データはメイン口座へ移します。'))return;const fallback=state.accounts.find(a=>a.id!==id);state.transactions.forEach(t=>{if(t.accountId===id)t.accountId=fallback.id;if(t.toAccountId===id)t.toAccountId=fallback.id});state.cards.forEach(c=>{if(c.accountId===id)c.accountId=fallback.id});state.fixedCosts.forEach(f=>{if(f.accountId===id)f.accountId=fallback.id});state.accounts=state.accounts.filter(a=>a.id!==id);persist()}
function setupPWA(){if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').then(r=>r.update()).catch(console.error);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('installBtn').hidden=false});const ios=/iphone|ipad|ipod/i.test(navigator.userAgent),standalone=matchMedia('(display-mode: standalone)').matches||navigator.standalone;if(ios&&!standalone)$('iosInstallCard').hidden=false}
function init(){applyAppearance();autoBackup();$('quickDate').value=todayKey();$('forecastHorizon').value=String(state.settings.forecastHorizon||60);renderSelects();bindForms();bindEvents();renderAll();setupPWA();const h=location.hash.replace('#','');if(['dashboard','shifts','budget','analysis','settings'].includes(h))navigate(h)}
init();
